class Cargo {
  late String _display;
  late String _name;
  late String _desc;
  late String _taxClassId;
  late String _logo;
  late String _sortOrder;
  late String _status;
  late String _group;
  late String _storeAll;
  late String _geoZoneAll;
  late String _cityAll;
  late String _city;
  late String _cityRule;
  late String _countryAll;
  late String _customerGroupAll;
  late String _paymentAll;
  late String _postalAll;
  late String _postal;
  late String _postalRule;
  late String _couponAll;
  late String _coupon;
  late String _couponRule;
  late String _category;
  late String _multiCategory;
  late String _product;
  late String _option;
  late String _manufacturerRule;
  late String _locationRule;
  late String _rateType;
  late String _dimensionalFactor;
  late String _cost;
  late List<String> _rateStart;
  late List<String> _rateEnd;
  late List<String> _rateTotal;
  late List<String> _rateBlock;
  late List<String> _ratePartial;
  late String _additional;
  late String _rateFinal;
  late String _ratePercent;
  late String _mask;
  late String _rateMin;
  late String _rateMax;
  late String _rateAdd;
  late String _equation;
  late List<String> _days;
  late String _timeStart;
  late String _timeEnd;
  late String _orderTotalStart;
  late String _orderTotalEnd;
  late String _weightStart;
  late String _weightEnd;
  late String _quantityStart;
  late String _quantityEnd;

  String get display => _display;
  set display(String display) => _display = display;
  String get name => _name;
  set name(String name) => _name = name;
  String get desc => _desc;
  set desc(String desc) => _desc = desc;
  String get taxClassId => _taxClassId;
  set taxClassId(String taxClassId) => _taxClassId = taxClassId;
  String get logo => _logo;
  set logo(String logo) => _logo = logo;
  String get sortOrder => _sortOrder;
  set sortOrder(String sortOrder) => _sortOrder = sortOrder;
  String get status => _status;
  set status(String status) => _status = status;
  String get group => _group;
  set group(String group) => _group = group;
  String get storeAll => _storeAll;
  set storeAll(String storeAll) => _storeAll = storeAll;
  String get geoZoneAll => _geoZoneAll;
  set geoZoneAll(String geoZoneAll) => _geoZoneAll = geoZoneAll;
  String get cityAll => _cityAll;
  set cityAll(String cityAll) => _cityAll = cityAll;
  String get city => _city;
  set city(String city) => _city = city;
  String get cityRule => _cityRule;
  set cityRule(String cityRule) => _cityRule = cityRule;
  String get countryAll => _countryAll;
  set countryAll(String countryAll) => _countryAll = countryAll;
  String get customerGroupAll => _customerGroupAll;
  set customerGroupAll(String customerGroupAll) =>
      _customerGroupAll = customerGroupAll;
  String get paymentAll => _paymentAll;
  set paymentAll(String paymentAll) => _paymentAll = paymentAll;
  String get postalAll => _postalAll;
  set postalAll(String postalAll) => _postalAll = postalAll;
  String get postal => _postal;
  set postal(String postal) => _postal = postal;
  String get postalRule => _postalRule;
  set postalRule(String postalRule) => _postalRule = postalRule;
  String get couponAll => _couponAll;
  set couponAll(String couponAll) => _couponAll = couponAll;
  String get coupon => _coupon;
  set coupon(String coupon) => _coupon = coupon;
  String get couponRule => _couponRule;
  set couponRule(String couponRule) => _couponRule = couponRule;
  String get category => _category;
  set category(String category) => _category = category;
  String get multiCategory => _multiCategory;
  set multiCategory(String multiCategory) => _multiCategory = multiCategory;
  String get product => _product;
  set product(String product) => _product = product;
  String get option => _option;
  set option(String option) => _option = option;
  String get manufacturerRule => _manufacturerRule;
  set manufacturerRule(String manufacturerRule) =>
      _manufacturerRule = manufacturerRule;
  String get locationRule => _locationRule;
  set locationRule(String locationRule) => _locationRule = locationRule;
  String get rateType => _rateType;
  set rateType(String rateType) => _rateType = rateType;
  String get dimensionalFactor => _dimensionalFactor;
  set dimensionalFactor(String dimensionalFactor) =>
      _dimensionalFactor = dimensionalFactor;
  String get cost => _cost;
  set cost(String cost) => _cost = cost;
  List<String> get rateStart => _rateStart;
  set rateStart(List<String> rateStart) => _rateStart = rateStart;
  List<String> get rateEnd => _rateEnd;
  set rateEnd(List<String> rateEnd) => _rateEnd = rateEnd;
  List<String> get rateTotal => _rateTotal;
  set rateTotal(List<String> rateTotal) => _rateTotal = rateTotal;
  List<String> get rateBlock => _rateBlock;
  set rateBlock(List<String> rateBlock) => _rateBlock = rateBlock;
  List<String> get ratePartial => _ratePartial;
  set ratePartial(List<String> ratePartial) => _ratePartial = ratePartial;
  String get additional => _additional;
  set additional(String additional) => _additional = additional;
  String get rateFinal => _rateFinal;
  set rateFinal(String rateFinal) => _rateFinal = rateFinal;
  String get ratePercent => _ratePercent;
  set ratePercent(String ratePercent) => _ratePercent = ratePercent;
  String get mask => _mask;
  set mask(String mask) => _mask = mask;
  String get rateMin => _rateMin;
  set rateMin(String rateMin) => _rateMin = rateMin;
  String get rateMax => _rateMax;
  set rateMax(String rateMax) => _rateMax = rateMax;
  String get rateAdd => _rateAdd;
  set rateAdd(String rateAdd) => _rateAdd = rateAdd;
  String get equation => _equation;
  set equation(String equation) => _equation = equation;
  List<String> get days => _days;
  set days(List<String> days) => _days = days;
  String get timeStart => _timeStart;
  set timeStart(String timeStart) => _timeStart = timeStart;
  String get timeEnd => _timeEnd;
  set timeEnd(String timeEnd) => _timeEnd = timeEnd;
  String get orderTotalStart => _orderTotalStart;
  set orderTotalStart(String orderTotalStart) =>
      _orderTotalStart = orderTotalStart;
  String get orderTotalEnd => _orderTotalEnd;
  set orderTotalEnd(String orderTotalEnd) => _orderTotalEnd = orderTotalEnd;
  String get weightStart => _weightStart;
  set weightStart(String weightStart) => _weightStart = weightStart;
  String get weightEnd => _weightEnd;
  set weightEnd(String weightEnd) => _weightEnd = weightEnd;
  String get quantityStart => _quantityStart;
  set quantityStart(String quantityStart) => _quantityStart = quantityStart;
  String get quantityEnd => _quantityEnd;
  set quantityEnd(String quantityEnd) => _quantityEnd = quantityEnd;

  Cargo.fromJson(Map<String, dynamic> json) {
    _display = json['display'].toString();
    _name = json['name'].toString();
    _desc = json['desc'].toString();
    _taxClassId = json['tax_class_id'].toString();
    _logo = json['logo'].toString();
    _sortOrder = json['sort_order'].toString();
    _status = json['status'].toString();
    _group = json['group'].toString();
    _storeAll = json['store_all'].toString();
    _geoZoneAll = json['geo_zone_all'].toString();
    _cityAll = json['city_all'].toString();
    _city = json['city'].toString();
    _cityRule = json['city_rule'].toString();
    _countryAll = json['country_all'].toString();
    _customerGroupAll = json['customer_group_all'].toString();
    _paymentAll = json['payment_all'].toString();
    _postalAll = json['postal_all'].toString();
    _postal = json['postal'].toString();
    _postalRule = json['postal_rule'].toString();
    _couponAll = json['coupon_all'].toString();
    _coupon = json['coupon'].toString();
    _couponRule = json['coupon_rule'].toString();
    _category = json['category'].toString();
    _multiCategory = json['multi_category'].toString();
    _product = json['product'].toString();
    _option = json['option'].toString();
    _manufacturerRule = json['manufacturer_rule'].toString();
    _locationRule = json['location_rule'].toString();
    _rateType = json['rate_type'].toString();
    _dimensionalFactor = json['dimensional_factor'].toString();
    _cost = json['cost'].toString();
    _rateStart = json['rate_start'].cast<String>();
    _rateEnd = json['rate_end'].cast<String>();
    _rateTotal = json['rate_total'].cast<String>();
    _rateBlock = json['rate_block'].cast<String>();
    _ratePartial = json['rate_partial'].cast<String>();
    _additional = json['additional'].toString();
    _rateFinal = json['rate_final'].toString();
    _ratePercent = json['rate_percent'].toString();
    _mask = json['mask'].toString();
    _rateMin = json['rate_min'].toString();
    _rateMax = json['rate_max'].toString();
    _rateAdd = json['rate_add'].toString();
    _equation = json['equation'].toString();
    _days = json['days'].cast<String>();
    _timeStart = json['time_start'].toString();
    _timeEnd = json['time_end'].toString();
    _orderTotalStart = json['order_total_start'].toString();
    _orderTotalEnd = json['order_total_end'].toString();
    _weightStart = json['weight_start'].toString();
    _weightEnd = json['weight_end'].toString();
    _quantityStart = json['quantity_start'].toString();
    _quantityEnd = json['quantity_end'].toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['display'] = this._display;
    data['name'] = this._name;
    data['desc'] = this._desc;
    data['tax_class_id'] = this._taxClassId;
    data['logo'] = this._logo;
    data['sort_order'] = this._sortOrder;
    data['status'] = this._status;
    data['group'] = this._group;
    data['store_all'] = this._storeAll;
    data['geo_zone_all'] = this._geoZoneAll;
    data['city_all'] = this._cityAll;
    data['city'] = this._city;
    data['city_rule'] = this._cityRule;
    data['country_all'] = this._countryAll;
    data['customer_group_all'] = this._customerGroupAll;
    data['payment_all'] = this._paymentAll;
    data['postal_all'] = this._postalAll;
    data['postal'] = this._postal;
    data['postal_rule'] = this._postalRule;
    data['coupon_all'] = this._couponAll;
    data['coupon'] = this._coupon;
    data['coupon_rule'] = this._couponRule;
    data['category'] = this._category;
    data['multi_category'] = this._multiCategory;
    data['product'] = this._product;
    data['option'] = this._option;
    data['manufacturer_rule'] = this._manufacturerRule;
    data['location_rule'] = this._locationRule;
    data['rate_type'] = this._rateType;
    data['dimensional_factor'] = this._dimensionalFactor;
    data['cost'] = this._cost;
    data['rate_start'] = this._rateStart;
    data['rate_end'] = this._rateEnd;
    data['rate_total'] = this._rateTotal;
    data['rate_block'] = this._rateBlock;
    data['rate_partial'] = this._ratePartial;
    data['additional'] = this._additional;
    data['rate_final'] = this._rateFinal;
    data['rate_percent'] = this._ratePercent;
    data['mask'] = this._mask;
    data['rate_min'] = this._rateMin;
    data['rate_max'] = this._rateMax;
    data['rate_add'] = this._rateAdd;
    data['equation'] = this._equation;
    data['days'] = this._days;
    data['time_start'] = this._timeStart;
    data['time_end'] = this._timeEnd;
    data['order_total_start'] = this._orderTotalStart;
    data['order_total_end'] = this._orderTotalEnd;
    data['weight_start'] = this._weightStart;
    data['weight_end'] = this._weightEnd;
    data['quantity_start'] = this._quantityStart;
    data['quantity_end'] = this._quantityEnd;
    return data;
  }
}

class Name {
  late String _s1;
  late String _s3;

  Name({required String s1, required String s3}) {
    this._s1 = s1;
    this._s3 = s3;
  }

  String get s1 => _s1;
  set s1(String s1) => _s1 = s1;
  String get s3 => _s3;
  set s3(String s3) => _s3 = s3;

  Name.fromJson(Map<String, dynamic> json) {
    _s1 = json['1'];
    _s3 = json['3'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['1'] = this._s1;
    data['3'] = this._s3;
    return data;
  }
}
