class Cart {
  late String _pdname;
  late String _model;
  late String _quantity;
  late String _image;
  late String _pprice;
  late String _cartId;
  late String _customerId;
  late String _productId;
  late String _recurringId;
  late String _option;
  late String _ocquantity;
  late String _dateAdded;
  late String _productOptionId;
  late String _optionId;
  late String _value;
  late String _required;
  late String _productOptionValueId;
  late String _optionValueId;
  late String _subtract;
  late String _sprice;
  late String _pricePrefix;
  late String _odname;
  late String _ovdname;
  late String _indirimprice;
  late String _indirimiktar;
  late String _totalprice;

  String get pdname => _pdname;
  set pdname(String pdname) => _pdname = pdname;
  String get model => _model;
  set model(String model) => _model = model;
  String get quantity => _quantity;
  set quantity(String quantity) => _quantity = quantity;
  String get image => _image;
  set image(String image) => _image = image;
  String get pprice => _pprice;
  set pprice(String pprice) => _pprice = pprice;
  String get cartId => _cartId;
  set cartId(String cartId) => _cartId = cartId;
  String get customerId => _customerId;
  set customerId(String customerId) => _customerId = customerId;
  String get productId => _productId;
  set productId(String productId) => _productId = productId;
  String get recurringId => _recurringId;
  set recurringId(String recurringId) => _recurringId = recurringId;
  String get option => _option;
  set option(String option) => _option = option;
  String get ocquantity => _ocquantity;
  set ocquantity(String ocquantity) => _ocquantity = ocquantity;
  String get dateAdded => _dateAdded;
  set dateAdded(String dateAdded) => _dateAdded = dateAdded;
  String get productOptionId => _productOptionId;
  set productOptionId(String productOptionId) =>
      _productOptionId = productOptionId;
  String get optionId => _optionId;
  set optionId(String optionId) => _optionId = optionId;
  String get value => _value;
  set value(String value) => _value = value;
  String get required => _required;
  set required(String required) => _required = required;
  String get productOptionValueId => _productOptionValueId;
  set productOptionValueId(String productOptionValueId) =>
      _productOptionValueId = productOptionValueId;
  String get optionValueId => _optionValueId;
  set optionValueId(String optionValueId) => _optionValueId = optionValueId;
  String get subtract => _subtract;
  set subtract(String subtract) => _subtract = subtract;
  String get sprice => _sprice;
  set sprice(String sprice) => _sprice = sprice;
  String get pricePrefix => _pricePrefix;
  set pricePrefix(String pricePrefix) => _pricePrefix = pricePrefix;
  String get odname => _odname;
  set odname(String odname) => _odname = odname;
  String get ovdname => _ovdname;
  set ovdname(String ovdname) => _ovdname = ovdname;
  String get indirimprice => _indirimprice;
  set indirimprice(String indirimprice) => _indirimprice = indirimprice;
  String get indirimiktar => _indirimiktar;
  set indirimiktar(String indirimiktar) => _indirimiktar = indirimiktar;
  String get totalprice => _totalprice;
  set totalprice(String totalprice) => _totalprice = totalprice;

  Cart.fromJson(Map<String, dynamic> json) {
    _pdname = json['pdname'].toString();
    _model = json['model'].toString();
    _quantity = json['quantity'].toString();
    _image = json['image'].toString();
    _pprice = json['pprice'].toString();
    _cartId = json['cart_id'].toString();
    _customerId = json['customer_id'].toString();
    _productId = json['product_id'].toString();
    _recurringId = json['recurring_id'].toString();
    _option = json['option'].toString();
    _ocquantity = json['ocquantity'].toString();
    _dateAdded = json['date_added'].toString();
    _productOptionId = json['product_option_id'].toString();
    _optionId = json['option_id'].toString();
    _value = json['value'].toString();
    _required = json['required'].toString();
    _productOptionValueId = json['product_option_value_id'].toString();
    _optionValueId = json['option_value_id'].toString();
    _subtract = json['subtract'].toString();
    _sprice = json['sprice'].toString();
    _pricePrefix = json['price_prefix'].toString();
    _odname = json['odname'].toString();
    _ovdname = json['ovdname'].toString();
    _indirimprice = json['indirimprice'].toString();
    _indirimiktar = json['indirimiktar'].toString();
    _totalprice = json['totalprice'].toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['pdname'] = this._pdname;
    data['model'] = this._model;
    data['quantity'] = this._quantity;
    data['image'] = this._image;
    data['pprice'] = this._pprice;
    data['cart_id'] = this._cartId;
    data['customer_id'] = this._customerId;
    data['product_id'] = this._productId;
    data['recurring_id'] = this._recurringId;
    data['option'] = this._option;
    data['ocquantity'] = this._ocquantity;
    data['date_added'] = this._dateAdded;
    data['product_option_id'] = this._productOptionId;
    data['option_id'] = this._optionId;
    data['value'] = this._value;
    data['required'] = this._required;
    data['product_option_value_id'] = this._productOptionValueId;
    data['option_value_id'] = this._optionValueId;
    data['subtract'] = this._subtract;
    data['sprice'] = this._sprice;
    data['price_prefix'] = this._pricePrefix;
    data['odname'] = this._odname;
    data['ovdname'] = this._ovdname;
    data['indirimprice'] = this._indirimprice;
    data['indirimiktar'] = this._indirimiktar;
    data['totalprice'] = this._totalprice;
    return data;
  }
}
